# This is a basic workflow to help you get started with Actions

name: update

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 deploy:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Update Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
              cd /pub/${{ secrets.USERNAME }}
              cd cmsc389T-web-template
              git pull
